# Generated by Django 2.0 on 2017-12-29 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0003_k_line_raw_trade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='k_line_raw',
            name='tick_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
