# Generated by Django 2.0 on 2017-12-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0005_k_line_raw_highvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k_line_raw',
            name='HighValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
