# Generated by Django 2.0 on 2017-12-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0006_auto_20171229_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='k_line_raw',
            name='LowValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='k_line_raw',
            name='RedGreen',
            field=models.CharField(default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='k_line_raw',
            name='TradeQty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
