version: "2"
services:
  redis:
    image: redis:alpine
  web:
    build:
      context: .
      dockerfile: compose/Dockerfile.redis
    image: liveblog_redis
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migrate
      - redis
  migrate:
    build:
      context: .
      dockerfile: compose/Dockerfile.redis
    image: liveblog_redis
    command: python manage.py migrate
    volumes:
      - .:/code
    links:
      - redis
